spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/movies_db
    username: postgres
    password: 1111
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: dev.profitsoft.internship.rebrov.blocktwo.config.CustomPostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db_changelog.xml
